development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: testing_development
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: testing_test
  pool: 5
  username: root
  password: 
  host: localhost
 
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: testing_production
  pool: 5
  username: root
  password: 
  host: localhost